-- CreateEnum
CREATE TYPE "OrderStatus" AS ENUM ('PENDING', 'COMPLETED', 'CANCELLED');

-- CreateEnum
CREATE TYPE "InventoryLogType" AS ENUM ('RESERVATION_CREATED', 'RESERVATION_EXPIRED', 'ORDER_CREATED', 'STOCK_ADJUSTMENT');
